docs(docusaurus/): documentation in docusaurus/
lulav-citros/citros pull request #25
Opened 2024-01-08 14:12 UTC by Yalyalieva

I put the documentation of the data analysis part to docusaurus/docs/data_analysis

2024-01-09 11:14 UTC, mariaBer requested changes
If I remember correctly we had a discussion about the documentation folder and if it should be under each category in data analysis or not, However I don't remember why the conclusion was to leave it in the way it is now.
Is it possible that thee documentation directory will be under each category rather than in documentation we will have again access, error etc.?

2024-01-09 11:14 UTC, mariaBer commented on docusaurus/docs/data_analysis/data_access/query_data.md
Some places you wrote: "Show the output:" , "the result", and some "Output table" any reason for the difference, if not
Please change them to "Show the output"  / "Show the result"

2024-01-10 18:49 UTC, mariaBer commented
@Yalyalieva, did you see the review?

2024-01-11 07:13 UTC, Yalyalieva commented
> @Yalyalieva, did you see the review?

Hi, @mariaBer , yes I saw the review and will work on it soon

2024-01-11 07:56 UTC, Yalyalieva commented
> If I remember correctly we had a discussion about the documentation folder and if it should be under each category in data analysis or not, However I don't remember why the conclusion was to leave it in the way it is now. Is it possible that thee documentation directory will be under each category rather than in documentation we will have again access, error etc.?

The documentation is made automatically and if there are references in methods to other classes they are also written automatically. It is the reasoin why documentation must repeate the structure of the package, otherwise the references will not work

2024-01-14 08:13 UTC, mariaBer commented on docusaurus/docs/data_analysis/index.md
> +## Table of Contents
Please change to see two levels rather than all of them

2024-01-15 08:20 UTC, merged